In [1]:
#import libraries
import pandas as pd
import numpy as np
import json
from pandas.io.json import json_normalize

In [2]:
#load word_bank_projects.jason
data=json.load((open('data/world_bank_projects.json')))

In [3]:
#Question1
#normalize data 
country=json_normalize(data)["countryname"]
#Find the 10 countries with most projects
country.value_counts().head(10)

People's Republic of China         19
Republic of Indonesia              19
Socialist Republic of Vietnam      17
Republic of India                  16
Republic of Yemen                  13
People's Republic of Bangladesh    12
Nepal                              12
Kingdom of Morocco                 12
Republic of Mozambique             11
Africa                             11
Name: countryname, dtype: int64

In [4]:
#Question2
#Find the top 10 major project themes (using column 'mjtheme_namecode')
themes = json_normalize(data,"mjtheme_namecode")
counts=themes.code.value_counts().head(10)
counts

11    250
10    216
8     210
2     199
6     168
4     146
7     130
5      77
9      50
1      38
Name: code, dtype: int64

In [5]:
#list the themecode and name
themename=themes.drop_duplicates(subset=None, keep='first', inplace=False).sort_values("name")
themename = themename.drop_duplicates(subset = "code", keep = "last", inplace = False)

In [6]:
#rename coloumn name of counts
#add index(code) as another coloumn 
counts=pd.DataFrame(counts)
counts.columns = ['counts']
counts["code"]=counts.index

In [7]:
#show both themecode and themenames by merge two dataframes
result=pd.merge(counts, themename, how='inner', on="code")
result.reindex(columns=["name","code","counts"])

                                           name code  counts
0  Environment and natural resources management   11     250
1                             Rural development   10     216
2                             Human development    8     210
3                      Public sector governance    2     199
4         Social protection and risk management    6     168
5      Financial and private sector development    4     146
6                   Social dev/gender/inclusion    7     130
7                         Trade and integration    5      77
8                             Urban development    9      50
9                           Economic management    1      38

In [8]:
#Question3
#sort by code and name
#replace '' with np.nan, then backfill NaN 
themes = json_normalize(data,"mjtheme_namecode")
themes=themes.sort_values(["code","name"]).replace('', np.nan).bfill()
themes.sort_index()

     code                                          name
0       8                             Human development
1      11  Environment and natural resources management
2       1                           Economic management
3       6         Social protection and risk management
4       5                         Trade and integration
5       2                      Public sector governance
6      11  Environment and natural resources management
7       6         Social protection and risk management
8       7                   Social dev/gender/inclusion
9       7                   Social dev/gender/inclusion
10      5                         Trade and integration
11      4      Financial and private sector development
12      6         Social protection and risk management
13      6         Social protection and risk management
14      2                      Public sector governance
15      4      Financial and private sector development
16     11  Environment and natural resources management
17      8                             Human development
18     10                             Rural development
19      7                   Social dev/gender/inclusion
20      2                      Public sector governance
21      2                      Public sector governance
22      2                      Public sector governance
23     10                             Rural development
24      2                      Public sector governance
25     10                             Rural development
26      6         Social protection and risk management
27      6         Social protection and risk management
28     11  Environment and natural resources management
29      4      Financial and private sector development
...   ...                                           ...
1469    8                             Human development
1470    9                             Urban development
1471    6         Social protection and risk management
1472    6         Social protection and risk management
1473    9                             Urban development
1474    2                      Public sector governance
1475    2                      Public sector governance
1476   10                             Rural development
1477   11  Environment and natural resources management
1478    8                             Human development
1479    7                   Social dev/gender/inclusion
1480   11  Environment and natural resources management
1481    5                         Trade and integration
1482    6         Social protection and risk management
1483    8                             Human development
1484    4      Financial and private sector development
1485    7                   Social dev/gender/inclusion
1486    8                             Human development
1487    5                         Trade and integration
1488    2                      Public sector governance
1489    8                             Human development
1490   10                             Rural development
1491    6         Social protection and risk management
1492   10                             Rural development
1493   10                             Rural development
1494   10                             Rural development
1495    9                             Urban development
1496    8                             Human development
1497    5                         Trade and integration
1498    4      Financial and private sector development

[1499 rows x 2 columns]

In [9]:
#count again top 10 project themes
#same anwser as counting code as previous 
counts2=themes.name.value_counts()
counts2

Environment and natural resources management    250
Rural development                               216
Human development                               210
Public sector governance                        199
Social protection and risk management           168
Financial and private sector development        146
Social dev/gender/inclusion                     130
Trade and integration                            77
Urban development                                50
Economic management                              38
Rule of law                                      15
Name: name, dtype: int64

In [10]:
#change to dataframe
counts2=pd.DataFrame(counts2)
counts2.columns = ["counts"]
counts2["name"]=counts2.index

In [11]:
#merge two dataframes to show both themename and themecode
result2 = pd.merge(counts2, themename, how = "inner", on = "name")
result2.reindex(columns=["name","code","counts"]).head(10)

                                           name code  counts
0  Environment and natural resources management   11     250
1                             Rural development   10     216
2                             Human development    8     210
3                      Public sector governance    2     199
4         Social protection and risk management    6     168
5      Financial and private sector development    4     146
6                   Social dev/gender/inclusion    7     130
7                         Trade and integration    5      77
8                             Urban development    9      50
9                           Economic management    1      38